### ISSUE TITLE
Support for status notifications

### ISSUE THREAD

**Issue by kolovos** [mondo-project/mondo-hawk#12]
It would be nice if some of the debug messages printed by Hawk could be transformed into proper status notifications that clients could subscribe to. Since indexing models can take a while, such notifications would help users get a feeling about how much progress has been made so far (e.g. Found new model foo.xmi, Indexing nodes, Created 5000/40000 nodes etc.). 

The Hawk view in Eclipse could show the last notification message (next to the location label of each Hawk?) and perhaps through a configuration option, users could choose whether they wish all events to be logged in Eclipse's Error Log view (e.g. as "information" items).

**Comment by bluezio** [comment]
We've implemented this between today and yesterday, both for the local and remote case. The Hawk view now has a fourth column called "Info" that shows simple one-liners with what the indexer is doing.
