### ISSUE TITLE
Querying Hawk while it's indexing a new file throws an exception

### ISSUE THREAD

**Issue by kolovos** [mondo-project/mondo-hawk#15]
Trying to run a query on Hawk through an EOL launch configuration produces a type-not-found exception. Steps to reproduce:

* Start a new Hawk with JDTAST and a local monitored folder
* Add set1.xmi to the monitored folder
* Try to run the following query while set1.xmi is being indexed

```
for (td in TypeDeclaration.all) {
	(td.name.fullyQualifiedName).println();
}
```

Ideally, the call to allOfKind should be blocked until Hawk is ready to process it. Alternatively, a dedicated exception could be thrown (e.g. HawkUpdateInProgressException)

**Comment by bluezio** [comment]
Hawk indexers can now accept IStateListener instances that are notified when the indexer changes state between RUNNING, STOPPED and UPDATING. With this, we're disabling the query UI during index updates and providing status messages.

We've extended this approach to the remote case in mondo-integration as well, using an Artemis queue to propagate these notifications to clients.

With this information, we should be able to also implement the second approach (throwing an exception), if the request manages to go through the UI anyway (for instance, Hawk starts updating right after the user presses the button and before the query is run).

**Comment by kb634** [comment]
Extended this approach to cover stand-alone Java applications (as well as OSGI-based) running Hawk with Epsilon, through Epsilon's UI and through Hawk's API.
