### ISSUE TITLE
Finish implementing functionality marked as TODO in HModel

### ISSUE THREAD

**Issue by bluezio** [mondo-project/mondo-hawk#20]
HModel has a few methods that have not been implemented yet: configuring polling, removing locations or removing indexed/derived attributes, for instance. These methods should be implemented sometime soon (perhaps after the training meeting, to avoid last minute regressions).

**Comment by bluezio** [comment]
Tiago just requested the ability to remove locations from Hawk.

**Comment by kb634** [comment]
All remaining methods are now functional, leaving issue open until further testing is done.

**Comment by kb634** [comment]
This issue seems resolved
