### ISSUE TITLE
Fully-qualified type names

### ISSUE THREAD

**Issue by kolovos** [mondo-project/mondo-hawk#21]
To reduce the need for fully-qualified type names, would it make sense to add a default namespace field to EOLQueryEngine? e.g.

```
EOLQueryEngine e = ...;
e.setDefaultNamespace("http://buildingsmart.ifc2x3tc1.ecore");
e.getAllOfType("IfcProject"); 
// instead of e.getAllOfType("http://buildingsmart.ifc2x3tc1.ecore::IfcProject");
```

**Comment by bluezio** [comment]
Shouldn't we be careful not to break references to unambiguous types, e.g. "Class"?

How would we expose this through the UI/Thrift API, however?

**Comment by bluezio** [comment]
This is now implemented and integrated into the Thrift API as well. Closing.
