### ISSUE TITLE
Cannot start Hawk after adding Capella metamodels and stopping Hawk

### ISSUE THREAD

**Issue by bluezio** [mondo-project/mondo-hawk#24]
@szarnyasg is trying to use Hawk with models conforming to the [Capella] metamodels, and is having issues when registering the metamodels. I tried registering them manually using the Eclipse UI for local and remote indexes, by adding all the .ecore files at once: most of them are registered fine, but Hawk complains about inter-metamodel dependencies a few times. (We later noticed that the Capella metamodels depend on the [KitAlpha] metamodels as well). I told him to sort all .ecore files according to their mutual dependencies: this is tedious but otherwise should work.

What is strange, however, is that if I register the Capella .ecore files and stop Hawk, I can't start Hawk again: it will get stuck with a "Registering metamodels" state. @kb634, could you look into this?

We should also think about how to simplify the registration of these complex metamodels: if we select a collection of .ecore files at once, shouldn't Hawk at least retry registration after it's done a first pass through the list of .ecore files? If could essentially work like this:

1. pending = selected
2. Go through pending and remove entries that are registered successfully, tracking their number.
3. If pending is not empty and we registered at least one metamodel last time we were in 2, go back to 2.
4. Otherwise, we're done.

[Capella]: http://git.polarsys.org/c/capella/capella.git/tree/core/plugins/org.polarsys.capella.core.data.gen/model
[KitAlpha]: https://www.polarsys.org/projects/polarsys.kitalpha

**Comment by szarnyasg** [comment]
Thanks for the issue! Also, please consider throwing an exception if the a required ecore model is not available.

**Comment by bluezio** [comment]
We fixed the problem about Hawk not restarting properly when you tried to add 2 or more unresolveable metamodels.

We've retried adding all the Capella/KitAlpha metamodels at once now, and some of them can be loaded, but many of these `.ecore` files depend on each other through `platform:/` URLs instead of namespace-based URLs or relative paths. Since Hawk is meant to work outside Eclipse workspaces (e.g. in the MONDO server), it does not support these URLs.

For now, I'd suggest replacing these inter-metamodel `platform:/`-based dependencies with something like `namespace#fragment` or `relative_path#fragment`. Those should work fine in Hawk.

**Comment by bluezio** [comment]
Closing issue for now.

**Comment by szarnyasg** [comment]
@bluezio thanks for the fix. Now I had another go with this problem.

> I told him to sort all .ecore files according to their mutual dependencies: this is tedious but otherwise should work.

I used Ecore Tools to visualize the dependencies, which would make the sorting much easier. However, it turned out that there is at least one circular dependency in Capella:

![image](https://cloud.githubusercontent.com/assets/1402801/11873185/94d33480-a4d9-11e5-836e-88a9c147c5a7.png)

[CapellaCommon.ecore](https://git.polarsys.org/c/capella/capella.git/tree/m2/plugins/org.polarsys.capella.core.data.def/model/CapellaCommon.ecore#n25) and [CapellaCore.ecore](https://git.polarsys.org/c/capella/capella.git/tree/m2/plugins/org.polarsys.capella.core.data.def/model/CapellaCore.ecore#n274) depend on each other so it's not possible to sort the ecore files according to their dependencies.

**Comment by bluezio** [comment]
Kostas told me that we already sorted them automatically (didn't know that!), but if there's a cyclic dependency I'm not sure if the current code will be able to cope. Have you tried adding those two .ecore files at once?

**Comment by bluezio** [comment]
Could you open another ticket for this cyclic dependency issue, by the way? Just to keep things tidy :-).
