### ISSUE TITLE
SVN connector: make it possible to index HEAD-1 instead of HEAD

### ISSUE THREAD

**Issue by bluezio** [mondo-project/mondo-hawk#29]
Through Skype, Istvan (from BME) told me that to use Hawk to back the collaboration framework, it'd have to index both the last and second last revisions of a model.

Modifying the update process to do this in general would be difficult, but it should be easy enough to provide an alternative SVN connector that indexes HEAD-1 instead of HEAD. It'd have to report a slightly modified URL, so we could use scoped queries to choose the version of the model that we wanted.

**Comment by kb634** [comment]
added SVNPrevManager to allow for indexing HEAD-1 (alongside the normal HEAD from SVNManager, if needed).
