### ISSUE TITLE
Metamodels can not be remove

### ISSUE THREAD

**Issue by etiennebrosse** [mondo-project/mondo-hawk#4]
In the indexer configuration the "Remove" button is never actif so it is not possible to remove a metamodel.
![removemetamodel](https://cloud.githubusercontent.com/assets/5493501/10396319/38d7bf92-6ea2-11e5-8117-a1731e36210a.png)

**Comment by bluezio** [comment]
This is a known limitation in Hawk at the moment. We'll be working on this very soon :-).

**Comment by alebagnato** [comment]
Thanks!

**Comment by kb634** [comment]
support added. please note that removing a metamodel will also remove any models which depend on it as well as any other metamodels that depend on it as well.

hawk will still monitor such files so if the appropriate metamodels are re-added to hawk the models will also be re-indexed.

please let me know if this works as expected and close the issue if it does.

**Comment by alebagnato** [comment]
Many thanks all, we'll test that asap

**Comment by bluezio** [comment]
We've been testing this feature and it's been working fine for us. Closing for now to keep the issues to a manageable number :-). Please feel free to reopen if you find any issues with it!

**Comment by alebagnato** [comment]
Many thanks for that! Nothing to report from our side as well!
