### ISSUE TITLE
Importing an EMF model in Hawk using Java

### ISSUE THREAD

**Issue by orichalque** [mondo-project/mondo-hawk#61]
Hi,

I just began to use Hawk in order to perform fast requests on models. I would like to integrate it in a project running under Maven, thus I followed the guide to build and use it this way, and so far it's working. 

I used some samples in the example repository of the project to set it up, and adding the EMF Metamodels (Ecore, and MoDisco's Java MM), i wrote a simple EOL query, that I would like to run on a MoDisco model, but I don't know how to add a Model to my instance of the ModelIndexer. 

Here's a sample of my code:

```
IModelIndexer modelIndexer = new ModelIndexerImpl("indexer", new File("~/hawk/"), null, new DefaultConsole());
modelIndexer.addMetaModelResourceFactory(new EMFMetaModelResourceFactory());

EMFModelResourceFactory emfModelResourceFactory = new EMFModelResourceFactory();
modelIndexer.addModelResourceFactory(emfModelResourceFactory);

IGraphDatabase db = (new Neo4JDatabase());
db.run(modelIndexer.getParentFolder(), modelIndexer.getConsole());

modelIndexer.setDB(db, true);
modelIndexer.setMetaModelUpdater(new GraphMetaModelUpdater());

File ecore = new File("src/test/resources/hawk/Ecore.ecore");
File mm = new File("src/test/resources/hawk/java.ecore");

File model = new File("src/test/resources/hawk/java.xmi");

modelIndexer.registerMetamodels(ecore);
modelIndexer.registerMetamodels(mm);

IQueryEngine iQueryEngine = new EOLQueryEngine();
modelIndexer.addQueryEngine(iQueryEngine);

modelIndexer.init(1000, 512 * 1000);

IHawkModelResource iHawkModelResource = emfModelResourceFactory.parse(null, model);

Object object = iQueryEngine.query(modelIndexer, "return EClass.all.size().println(\"All classes: \");", new HashMap<>());
System.out.println(object); // 0
```

Could you how I could use to run this EOL query on my xmi model ? 
Thank you :-)

**Comment by kb634** [comment]
Hi Orichalque,

Hawk knows about models by monitoring folder locations, in either local or remote directories.
As such, in order to query your model, you would first have to add the folder it is contained in to Hawk.
The simplest driver to use is the LocalFolder driver, which will simply need a local folder path to monitor.

After Hawk has at least one monitored location, every time it synchronizes, it will update its internal store with any new or changed model files found in that location, that it is "interested in". This would mean any models that are of a modeling technology the current running Hawk instance knows about, in your case EMF models, as you have added an EMFModelResourceFactory in your code.

 As such, I would replace these two lines:
```
File model = new File("src/test/resources/hawk/java.xmi");
IHawkModelResource iHawkModelResource = emfModelResourceFactory.parse(null, model);
```

With the following:
```
LocalFolder toMonitor = new LocalFolder();
toMonitor.init("src/test/resources/hawk/", modelIndexer);
```

All of which should be written before the 
```
modelIndexer.init(1000, 512 * 1000); 
```
statement.

Please let us know if this solves your issue,

Cheers,

**Comment by orichalque** [comment]
Hi, 
I replaced my code according to those modifications, however when I try to run EOL Queries on my model, I'm never getting any results:


```

File ecore = new File("src/test/resources/hawk/Ecore.ecore");
File mm = new File("src/test/resources/hawk/java.ecore");

modelIndexer.registerMetamodels(ecore);
modelIndexer.registerMetamodels(mm);

IQueryEngine iQueryEngine = new EOLQueryEngine();
modelIndexer.addQueryEngine(iQueryEngine);

LocalFolder localFolder = new LocalFolder();
localFolder.init("src/test/resources/hawk/", modelIndexer);

modelIndexer.init(1000, 512 * 1000);

iQueryEngine.query(modelIndexer, "MethodDeclaration.all.size().println(\"number of methods: \");", new HashMap<>());
```
And the only result I'm getting is: `number of methods: 0`.

My project is organized in that way: 

```
└── test
    └── resources
        ├── hawk
            ├── Ecore.ecore
            ├── java.ecore
            └── junit_java.xmi
```

Do you think that the fact that I put my model in the same directory as the metamodels is wrong? Or my parameters ? 

Thank you for your help

**Comment by bluezio** [comment]
I would recommend that you do not place your metamodels in the same folder as the model. Hawk will end up indexing the metamodels as models, so you will have unwanted elements in your index.

I would recommend having a look at our JUnit tests as a reference for indexing from plain Java:

https://github.com/mondo-project/mondo-hawk/blob/master/tests/org.hawk.integration.tests/src/org/hawk/integration/tests/ModelIndexingTest.java#L133

Specifically, you seem to be missing the lines that add the metamodel and model updaters to Hawk. Without these components, Hawk will see the changes in your local folder but will not know how to update the graph accordingly.  These components should be added before you try to register any metamodels or model locations.

Also, when you add a location to be indexed, you must `run()` it and add it to the indexer. See here:

https://github.com/mondo-project/mondo-hawk/blob/master/tests/org.hawk.integration.tests/src/org/hawk/integration/tests/ModelIndexingTest.java#L195

**Comment by bluezio** [comment]
By the way, you can't query straight away after the init(). You have to wait until synchronisation is done, and then you can run the query. For instance, check this JUnit test case:

https://github.com/mondo-project/mondo-hawk/blob/master/tests/org.hawk.integration.tests/src/org/hawk/integration/tests/emf/CountInstancesTest.java#L54

**Comment by orichalque** [comment]
Hi,
Thank you very much for those references, I'm going to look at that thoroughly.

**Comment by orichalque** [comment]
Hey, I applied those changes and it is now working amazingly well. Thank you very much for your help !
