### ISSUE TITLE
Returning instance of an EObject after EOL Query

### ISSUE THREAD

**Issue by orichalque** [mondo-project/mondo-hawk#62]
Hi,

I'm encountering some troubles with Hawk, I hope that you can help me.
Following the advice you gave me already I managed to load my model, and running some small EOL Queries on it.

However, I cannot find a way of getting the result of the query when it is an object from my model. 

For instance, when running the query: 
`queryEngine.query(modelIndexer, "return JavaNodeSourceRegion.all.size();", null);`
The object returned is an instance of java.lang.Integer, as expected.

But the query:
`queryEngine.query(modelIndexer, "return JavaNodeSourceRegion.all.select(j|j.startLine="+lineStart+").first();", null);`
does not return an instance of a JavaNodeSourceRegion, but a  org.hawk.epsilon.emc.wrappers.GraphNodeWrapper, and I cannot find a way of getting my object instance with it.

Is there a way of getting the instance of my JavaNodeSourceRegion from this query ? 

Thank you for your help :)

**Comment by bluezio** [comment]
The query runs within the graph and produces a graph node as its result, as expected. The core of Hawk is completely EMF-agnostic: you have to map it back to an EObject. (By the way, remember that Hawk indices are entirely read-only!)

You can either map it to a virtual, read-only EObject, or you can try to map it back to the original EObject it was loaded from. If you are OK with a virtual, read-only EObject (much more efficient), you could use the [LocalHawkResourceImpl](https://github.com/mondo-project/mondo-hawk/blob/master/plugins/org.hawk.emfresource/src/org/hawk/emfresource/impl/LocalHawkResourceImpl.java#L306) class, which has a fetchByQuery method which is exactly for this purpose.

If you need the physical EObject from the original .xmi file, then you can always rebuild the full EMF EObject's URI and use that to load the proper .xmi file and fetch an EObject from the EResource by fragment. [HawkCrossReferences](https://github.com/mondo-project/mondo-hawk-emfsplitter/blob/master/org.hawk.emf.emfsplitter/src/org/hawk/emf/emfsplitter/HawkCrossReferences.java#L410) in `hawk-emfsplitter` does just that.

**Comment by orichalque** [comment]
Hi @bluezio ,
In fact I only need a read-only EObject, the `LocalHawkResourceImpl` class seems nice for that purpose. 
Thank you very much for your answer, this helps a lot.

**Comment by bluezio** [comment]
No worries! Feel free to close the issue if you think this is enough info. Let me know if you need more clarifications on how to use it - I think we don't have automated unit tests for that one yet, so sadly I cannot point you at the moment to an end-to-end example.

**Comment by bluezio** [comment]
Closing for now - feel free to reopen if you run into issues!
