### ISSUE TITLE
eContainer throws exception when not contained

### ISSUE THREAD

**Issue by beatrizsanchez** [mondo-project/mondo-hawk#68]
Asking on a non-contained model element `me.eContainer` throws an error even when asking if its null
```
if (me.eContainer <> null){
	me.eContainer.println("eContainer");
}
// throws
eContainer failed,
OrientNode [#57:130225]
is not contained
```
Maybe we should add a `isContained` method for model elements?

**Comment by bluezio** [comment]
Just in case, I have changed it so eContainer will simply return null if the element is not contained. Added a test case that makes sure this will stay this way :-).
