### ISSUE TITLE
When running multiple EOL queries, only the first one will work

### ISSUE THREAD

**Issue by orichalque** [mondo-project/mondo-hawk#69]
Hello,

I'm currently trying to run several EOL queries, one by one, on my model. ([In this class](https://github.com/atlanmod/MDE4RTS/blob/master/parsing/src/test/java/com/tblf/parsing/HawkQueryTest.java))
The very first one will run smoothly, however the next ones will always return `null`.

My queries are really simple, consisting in running `return MyClass.all.size();`, and are executed [this way](https://github.com/atlanmod/MDE4RTS/blob/master/parsing/src/main/java/com/tblf/parsing/indexer/HawkQuery.java): 

```
waitForSync(modelIndexer, () ->
             modelIndexer.getKnownQueryLanguages().get("org.hawk.epsilon.emc.EOLQueryEngine").query(modelIndexer, query, null));
sem.release(); //A semaphore, in order to only run one query at once

```

The `waitForSync` method is the following, slightly modified from the ones available in Hawk test suites:
```
private Object waitForSync(IModelIndexer indexer, final Callable<?> r) {
    final SyncEndListener changeListener = new SyncEndListener(r, sem);
    indexer.addGraphChangeListener(changeListener);
    try {
        if (!sem.tryAcquire(180, TimeUnit.SECONDS)) {
            throw new RuntimeException("Synchronization timed out");
        } else {
            indexer.removeGraphChangeListener(changeListener);
            if (changeListener.getThrowable() != null)
                throw changeListener.getThrowable();
        }
    } catch (Throwable e) {
        LOGGER.log(Level.WARNING, "Error with indexer synchronization", e);
    }

    return changeListener.getReturnValue();
}
```
The [SyncEndListener](https://github.com/atlanmod/MDE4RTS/blob/master/parsing/src/main/java/com/tblf/parsing/indexer/SyncEndListener.java) has been overridden in order to easily get a return value.

Is there any operation I should do between each query, in order to put the ModelIndexer in the "right configuration"  ?

Thank you for your help

**Comment by bluezio** [comment]
Sorry for the delay: I have been busy with a paper and helping out with our student-run software company at my university :-).

You do not need to release the semaphore yourself: the SyncEndListener is doing that already. I don't see anything obviously wrong with your code, but I will try to run it now.

**Comment by bluezio** [comment]
I have tried running your class and it seems I am missing a few libraries, even though I have imported all dependencies through Maven. Within HawkQuery, I seem to be missing these imports:

```
import org.eclipse.modisco.java.composition.javaapplication.Java2File;
import org.eclipse.modisco.kdm.source.extension.ASTNodeSourceRegion;
```

How can I set up a dev environment for your code?

**Comment by bluezio** [comment]
OK, I noticed one thing: you are calling waitForSync too often :-D. You don't need to do it before every query, but rather only after you have set up the index, so you will wait for the graph to be ready for querying.

Another thing: did you check the log to see if Hawk produced any errors? It should only return null if there was an error running the EOL query. I'd need some Hawk diagnostic information to go on looking, or at least a way to run your tests.

**Comment by bluezio** [comment]
That's great to know! Closing this issue, then :-).
