### ISSUE TITLE
Using the Hawk Thrift Java API

### ISSUE THREAD

**Issue by beatrizsanchez** [mondo-project/mondo-hawk#71]
Hi, 

I have been trying to run and use hawk programmatically from Java. I have succeeded in interacting with Hawk in a similar way as how the `org.hawk.service.cli` uses Hawk, that is, consuming the `org.hawk.service.api` and `org.hawk.service.artemis` plugins and interacting with the `Hawk.Client` class. However, I've noticed that the `Hawk` class from `org.hawk.service.api` does not offer methods from the Thrift API as indicated in the [wiki](https://github.com/mondo-project/mondo-hawk/wiki/Thrift-API). 

For example, I cannot call 
```
Hawk.createInstance(...)
``` 
as in the Thrift API wiki, but instead I have to call 		

```
Hawk.Client client = ...;
client.createInstance(...);
```

I imagine the differences come from the fact that I have not build properly the API as indicated [here](https://github.com/mondo-project/mondo-hawk/wiki/Building-the-Thrift-API-client-with-plain-Maven). The problem I face on how to build the Thrift API is that I cannot find a `pom-server-plain.xml` file so I have tried the following:

- Running `mvn -f pom-plain.xml install` at the root of the Hawk project 
- Running `mvn -f pom-plain.xml install` at the root of `org.hawk.service.api`. This brought a lot of compilation errors, then again, so did the former command but they disappeared after a clean build in Eclipse. I wonder if I should try this again.
- Running `install-maven-deps.sh` at the root of the Hawk project
- Running `generate.sh` in the `org.hawk.service.api` project. This crashes with `line 5: thrift: command not found` and `line 6: thrift: command not found`.

My questions are: 

- What am I missing to properly build the Thrift API ?
- Is the API wiki outdated and we have to use hawk as in the CLI project?
- Is there any chance the API could be published in maven or any other dependency repository to be included in arbitrary Java scripts that connect to a Hawk Server?

**Comment by beatrizsanchez** [comment]
Ok, I've installed Thrift in my machine. My bad! I thought that only the dependency was necessary. 
I've re-ran the `generate.sh` with Thrift 0.9.3 installed and it worked! I initially tried with Thrift compiler (0.11.0) but brought several compilation issues. 

After I ran the `generate.sh` I executed `mvn -f pom-plain.xml install` and was able to use the dependency from my local maven repository.

**Comment by bluezio** [comment]
The `pom-plain.xml` file does build the API module, so that should just work :-/. Travis is also happy:

https://travis-ci.org/mondo-project/mondo-hawk/jobs/458528114

In any case, yes - you have to use `Hawk.Client` and not just `Hawk`. This is because of the way Thrift generates the code - it doesn't have anything to do with whether you use .api as a plugin or as a JAR library. Hawk is interface, and Hawk.Client is the specific implementation that Thrift instantiates for you :-).

**Comment by beatrizsanchez** [comment]
Thanks Antonio!
