### ISSUE TITLE
HawkQueryOptions doesn't seem to work with thrift json queries

### ISSUE THREAD

**Issue by kaischaabouni** [mondo-project/mondo-hawk#77]
When I send this POST request to : http://localhost:8080/thrift/hawk/json
with the JSON body :
`[1,"query",1,1,{"1":{"str":"InstanceName"},"2":{"str":"return Concept.latest.all.size;"},"3":{"str":"org.hawk.timeaware.queries.TimeAwareEOLQueryEngine"},"4":{"rec":{"1":{"str":"https://<MySvnUrl>/trunk/model"}}}}]`

It should indicate in HawkQueryOptions that repositoryPattern = "https://<MySvnUrl>trunk/model". However, I receive the same response as if repositoryPattern="*"

**Comment by bluezio** [comment]
Thank you for the report! The current version of TimeAwareEOLQueryEngine is an early prototype and it was missing the support for context-based filters, such as repositoryPattern or filePattern.

I will look into reintroducing these features into the time-aware EOL query engine ASAP :-).

**Comment by bluezio** [comment]
I have added a test for this and made it pass (after a good amount of refactoring!). It should work now - you will need to upgrade your server at the very least, and I would recommend you upgrade your client as well.

You should be able to update your Eclipse installation through the update site, and use the new snapshot of the servers which are now built automatically by Travis and hosted on Bintray.

Update site is here:

http://mondo-project.github.io/mondo-hawk/updates/

The updated server is here:

https://dl.bintray.com/bluezio/generic/

You could in theory upgrade the server in place by using the p2 director app with `-removeIU` first and then with `-installIU` (as described in [our docs](https://github.com/mondo-project/mondo-hawk/wiki/Deploying-and-running-the-server)), but it's quite finicky.

Closing as resolved for now - feel free to reopen if this does not fully resolve the issue for you!
