### ISSUE TITLE
Adding metamodel errors are logged, but not informed to user

### ISSUE THREAD

**Issue by arcanefoam** [mondo-project/mondo-hawk#87]
When adding a new metamodel the URI is not added to the list of metamodels after selecting the ecore file in the explorer.
Looking at the log there is an entry for the error:

`!MESSAGE org.hawk.graph.updater.GraphMetaModelResourceInjector  - EAttribute name has type EString which is in a package not registered yet, reverting all changes to this package registration, please register package with URI: http://www.eclipse.org/emf/2002/Ecore first`

This error/warning should be presented to the user. For this particular case, it would be nice if Hawk could detect that the metamodel is actually ecore and ask if it should add it automatically. 
Further, it should be possible to add metamodels from the eclipse registry (this is probably another bug). In the ecore case, it is cumbersome to need to find an ecore metamodel instance somewhere...

The documentation should probably mention something about metamodel dependencies and how they should be added respecting the dependency order.

**Comment by bluezio** [comment]
The main issue is that this error is several layers below under a separate scheduling layer, and propagating this without blocking the UI is more complicated that it seems. I'll look into it and see what I can do.

I would suggest creating separate issues for the ability to add metamodels from the eclipse registry, as you say. A pull request would be definitely welcome. Hawk at the moment does not have a generic interface for components that can "import" metamodels: this would need to be done in a generic, EMF-agnostic way.

I have tweaked the documentation to explicitly mention the need to consider dependencies when adding metamodels.
